AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Exclude:
    - lib/safe-pg-migrations.rb
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
    Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/NumericPredicate:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
