# DON'T MODIFY THIS WORKFLOW FILE DIRECTLY
#
# This workflow
# - checks if the PR title is compliant
# (cf. https://doctolib.atlassian.net/wiki/spaces/EE/pages/1793131314/How+to+have+a+good+PR+title)
# - is force implemented in specific repositories (tier0 repository) of the organization with Terraform
# - is mandatory to merge in main branch of your repo because of
# https://github.com/doctolib/kube/blob/master/envs/tooling/terraform/05_github/main_rulesets.tf#L1
#
# For more details, read https://doctolib.atlassian.net/wiki/spaces/EE/pages/1793590015/Traceability+and+risk+assessment+for+production+changes

name: '[Org workflow] Check PR title'
run-name: '${{ github.event.pull_request.title }}'

on:
  pull_request:
    branches: [master, main, staging]
    types: [opened, edited, reopened, synchronize, ready_for_review]
  merge_group:

permissions:
  pull-requests: write
  statuses: write
  repository-projects: read
  actions: read

jobs:
  check_pr_title:
    name: Check PR title
    if: '!github.event.pull_request.draft'
    runs-on: prod-linux-xs
    steps:
      - name: Check PR title
        uses: doctolib/actions/check-pr-title@main
