env:
  RUBY_VERSION: 3.4.8
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: safe_pg_migrations_test
  PGPASSWORD: postgres
  TESTOPTS: --verbose

name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: doctolib/actions/setup-ruby@fe60c5c88629515edae76e8c2f90c381995ca0ce # setup-ruby-v0.0.25
      - name: Check code
        run: bundle exec rubocop
  unit-test:
    name: UnitTest
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    strategy:
      matrix:
        postgres: [ 11.7, 12.14, 15.2 ]
        ruby: [ "3.3", "3.4" ]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_DB: safe_pg_migrations_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set Ruby version
        run: echo "${{ matrix.ruby }}" > .ruby-version
      - uses: doctolib/actions/setup-ruby@fe60c5c88629515edae76e8c2f90c381995ca0ce # setup-ruby-v0.0.25
      - name: Run tests
        run: bundle exec rake test
  legacy-activerecord-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.3"
            gemfile: gemfiles/without_strong_migrations.gemfile
          - ruby: "3.3"
            gemfile: gemfiles/activerecord61.gemfile
          - ruby: "3.3"
            gemfile: gemfiles/activerecord70.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    services:
      postgres:
        image: postgres:12.9
        env:
          POSTGRES_DB: safe_pg_migrations_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set Ruby version
        run: echo "${{ matrix.ruby }}" > .ruby-version
      - uses: doctolib/actions/setup-ruby@fe60c5c88629515edae76e8c2f90c381995ca0ce # setup-ruby-v0.0.25
      - name: Run tests
        run: bundle exec rake test
